### ISSUE TITLE
Docker-compose:  Service 'portal-frontend' failed to build

### ISSUE THREAD

**Issue by vetsolution** [certat/do-portal#113]
Hello,

I cant build do-portal with the docker--comose file provided.
A log of the last line of the build: 
```
Step 13/16 : RUN    cp config/envs/docker.json config/envs/devel.json     && cp config/envs/docker.json config/envs/production.json     && PATH=$(npm bin):$PATH grunt
 ---> Running in 3ffa5019df08
Loading "Gruntfile.js" tasks...ERROR
>> Error: Unable to read "secret.json" file (Error code: ENOENT).

jit-grunt: Plugin for the "default" task not found.
If you have installed the plugin already, please setting the static mapping.
See https://github.com/shootaroo/jit-grunt#static-mappings

Warning: Task "default" failed. Use --force to continue.

Aborted due to warnings.


Execution Time (2020-03-25 09:35:07 UTC-0)
loading tasks  131ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 99%
Total 132ms

ERROR: Service 'portal-frontend' failed to build: The command '/bin/sh -c cp config/envs/docker.json config/envs/devel.json     && cp config/envs/docker.json config/envs/production.json     && PATH=$(npm bin):$PATH grunt' returned a non-zero code: 3

```
Any one encounter this ? 

Many thanks

**Comment by MarkHofstetter** [comment]
hi, 
which branch are you trying to build, (and just out of personal interest what are you planing to do?)

cheers
Mark

**Comment by vetsolution** [comment]
Hello Mark, 
I'm on the master branch.
It seem that is the command 'PATH=$(npm bin):$PATH grunt' which cause troubles.

I want to have a platform where I can centralize and treat several security feeds, so I look after IntelMQ for the centralization and now I'm looking for an interface to ease the analysis of the events

Regards

**Comment by MarkHofstetter** [comment]
I just added an example for secret.json to the master branch it should work now.

But I doubt that this part of the software is going to help you much with IntelMQ. This is some sort of a hierarchical contact database for "certs"

**Comment by wagner-certat** [comment]
> I want to have a platform where I can centralize and treat several security feeds, so I look after IntelMQ for the centralization and now I'm looking for an interface to ease the analysis of the events

This software is mainly for management of contact information with an integration (lookup) for IntelMQ. An optional component is the stats portal, but I recommend to use it stand-alone if you do not need the rest of this.

For a broader discussion I invite you to join the mailinglist, where you can ask for ideas on what you are trying to achieve. There are various users there which could also add some experience and insights:
https://lists.cert.at/cgi-bin/mailman/listinfo/intelmq-users

**Comment by vetsolution** [comment]
I pull the last revision and I still encounter the issue. 
I'm not very familiar with npm stuff so it is difficult for me to debug what going on.

I'm interested in the contact database

Thank you for your help

**Comment by wagner-certat** [comment]
@davewood Can you have a look please?

**Comment by MarkHofstetter** [comment]
and you copied secret.json.example to secrete.json?

**Comment by vetsolution** [comment]
Nope misread your previous comment, it builds now ;)
Maybe specify it install doc ? https://github.com/certat/do-portal/blob/master/docs/01_INSTALL.md

Thank you

**Comment by wagner-certat** [comment]
Thanks for the bug report @vetsolution and for the fix @MarkHofstetter
